#!/bin/bash

# Script de instalacao do Arch Linux
# Contato Telegram: @rocker_raccoon
# Atualizado: 02/03/2020

clear ; echo -e '\t\t\t\tScript de instalacao do Arch Linux \n\nAtive a particao swap e monte as unidades destino antes de continuar... \n'

echo -e "Continuar? [ S ou s = SIM ]" ; read yorn
    if [[ $yorn = [sSyY] ]]; then
    
while true
    do
    clear ; echo -n "Digite o nome do usuario: " ; read nn1
    sleep 1s ; echo -n "Confirme o nome do usuario: " ; read nn2
    if [[ "$nn1" == *"$nn2"* ]]
    then
    break
    else
    clear ; echo "Os nomes nao coincidem. Tente novamente! " ; sleep 2s
    fi
done

trap '' INT TSTP

pacstrap /mnt base base-devel linux linux-firmware linux-headers dhcpcd nano grub xorg-server xorg-xinit xorg-xrandr wget git p7zip unrar gvfs ttf-dejavu zsh networkmanager

sed -i '/pt_BR.UTF-8/,+1 s/^#//' /mnt/etc/locale.gen

echo "LANG=pt_BR.UTF-8" > /mnt/etc/locale.conf

arch-chroot /mnt locale-gen

genfstab -U /mnt >> /mnt/etc/fstab

clear ; echo -e "\nGRUB\n----\n\n1) BIOS\t\t\t2) UEFI\t\t\t3) Nao definir\n" ; echo -n "Escolha [1-3]: " ; read g
case $g in
    1) clear ; echo -n 'Indique o disco onde o GRUB sera instalado. Ex.: sda, sdb, sdc: ' ; read dgrb ; arch-chroot /mnt grub-install /dev/$dgrb ; arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg ;;
    2) arch-chroot /mnt pacman -S --needed --noconfirm efibootmgr ; arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub --recheck ; arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg ;;
    3) break ;;
esac

#grbb=`lsblk | grep /mnt | sed -n '1p' |cut -c3-5`

echo "archlinux" > /mnt/etc/hostname

arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Recife /etc/localtime

#outras opcoes
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Araguaina /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Bahia /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Belem /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Belize /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Boa_Vista /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Buenos_Aires /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Campo_Grande /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Cuiaba /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Fortaleza /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Maceio /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Manaus /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Noronha /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Porto_Acre /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Porto_Velho /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Recife /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Rio_Branco /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Santarem /etc/localtime
#arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

cat << EOF > /mnt/etc/vconsole.conf
KEYMAP=br-abnt2
FONT=Lat2-Terminus16
FONT_MAP=
EOF

mkdir -p /mnt/etc/X11/xorg.conf.d/
cat << EOF > /mnt/etc/X11/xorg.conf.d/01-keyboard-layout.conf
Section "InputClass"
         Identifier "Keyboard Defaults"
         MatchIsKeyboard "yes"
         Option "XkbLayout" "br"
EndSection
EOF

arch-chroot /mnt git clone https://github.com/ohmyzsh/ohmyzsh /etc/skel/.oh-my-zsh
arch-chroot /mnt git clone https://github.com/zsh-users/zsh-autosuggestions.git /etc/skel/.oh-my-zsh/plugins/zsh-autosuggestions
arch-chroot /mnt git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /etc/skel/.oh-my-zsh/plugins/zsh-syntax-highlighting
wget https://github.com/dylanaraps/neofetch/raw/master/neofetch -O /mnt/usr/local/bin/neofetch
wget https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev -O /mnt/usr/local/bin/screenfetch
chmod +x /mnt/usr/local/bin/*
cp /mnt/etc/skel/.oh-my-zsh/templates/zshrc.zsh-template /mnt/etc/skel/.zshrc
sed -i 's/en_US/pt_BR/' /mnt/etc/skel/.oh-my-zsh
sed -i '/pt_BR/s/^#//' /mnt/etc/skel/.oh-my-zsh

sed -i 's/(git)/(git compleat common-aliases extract zsh-autosuggestions zsh-syntax-highlighting)/'

clear ; echo 'senha do root '
arch-chroot /mnt passwd

arch-chroot /mnt groupadd -r autologin
arch-chroot /mnt useradd -m -g users -G autologin,wheel,storage,power -s /bin/bash $nn1

clear ; echo 'senha do '$nn1' '
arch-chroot /mnt passwd $nn1
arch-chroot /mnt chsh -s /bin/zsh $nn1

sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /mnt/etc/sudoers

arch-chroot /mnt systemctl enable dhcpcd
arch-chroot /mnt systemctl enable NetworkManager

arch-chroot /mnt chown -R $nn1:$nn1 /home/$nn1 ; arch-chroot /mnt chown -R ${nn1}:${nn1} /home/$nn1

clear ; echo -e "Instalacao concluida. Reiniciar? [ S ou s = SIM ]" ; read yorn
    if [[ $yorn = [sSyY] ]]; then
    umount -R /mnt && reboot
    fi
    
    else
    exit
    fi
