#!/bin/bash

# sincroniza a data do sistema com o horario obtido na internet
echo -e '[Time]\nNTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org\nFallbackNTP=0.pool.ntp.org 1.pool.ntp.org 0.fr.pool.ntp.org' | sudo tee /etc/systemd/timesyncd.conf ; sudo timedatectl set-ntp true
