#!/bin/bash

sudo wget --no-check-certificate https://github.com/dylanaraps/neofetch/raw/master/neofetch -P /usr/local/bin ; sudo chmod +x /usr/local/bin/*

OU

wget --no-check-certificate https://github.com/dylanaraps/neofetch/raw/master/neofetch -P ~/.bin ; chmod +x ~/.bin/neofetch

exit
