#!/bin/bash

# Script de instalacao do Arch Linux (SIAL)
# Contato Telegram: @rocker_raccoon
# Atualizado: 02/03/2020

clear ; echo -e '\t\t\t\tScript de instalacao do Arch Linux \n\nAtive a particao swap e monte as unidades destino antes de continuar... \n'

echo -n 'Continuar? [ S ou s = SIM ] ' ; read yorn
    if [[ $yorn = [sSyY] ]]; then
    
trap '' INT TSTP

	if [ -d /mnt/var/cache/pacman/pkg ]; then
	echo ; echo -n 'Deseja reutilizar o cache da instalacao anterior ? [ S ou s = SIM ] ' ; read pcial
	if [[ $pcial = [sSyY] ]]; then
	echo -e '\nAguarde... \n'
	mv /mnt/var/cache/pacman/pkg /mnt/.p
	rm -rf /mnt/*
	mkdir -p /mnt/var/cache/pacman
	mv /mnt/.p /mnt/var/cache/pacman/pkg
	fi
	fi
    
echo -n 'Digite o nome do usuario: ' ; read nnu ; echo
echo -n 'Digite um nome para a maquina (hostname): ' ; read nmq
clear
echo -e '\nDesktop Environment\n-------------------\n\n1) XFCE\t\t2) Mate\t\t3) Plasma\t4) Cinnamon\t5) Nenhum\n' ; echo -n 'Escolha [1-5]: ' ; read g
case $g in
    1) setde='xfce4 pulseaudio pavucontrol ristretto thunar-archive-plugin xfce4-clipman-plugin xfce4-notifyd xfce4-pulseaudio-plugin xfce4-screensaver xfce4-screenshooter xfce4-whiskermenu-plugin file-roller gnome-calculator' ; mkdir -p /mnt/etc/skel/ ; echo 'exec startxfce4' >> /mnt/etc/skel/.xinitrc ; echo 'startx' >> /mnt/etc/skel/.zprofile ;;
    2) setde='mate pulseaudio engrampa eom mate-applets mate-calc mate-media mate-power-manager mate-screensaver mate-system-monitor mate-terminal mate-utils' ; mkdir -p /mnt/etc/skel/ ; echo 'exec mate-session' >> /mnt/etc/skel/.xinitrc ; echo 'startx' >> /mnt/etc/skel/.zprofile ;;
    3) setde='plasma pulseaudio konsole dolphin ark' ; mkdir -p /mnt/etc/skel/ ; echo 'exec startplasma-x11' >> /mnt/etc/skel/.xinitrc ; echo 'startx' >> /mnt/etc/skel/.zprofile ;;
    4) setde='cinnamon pulseaudio gnome-terminal file-roller eog gnome-calculator' ; mkdir -p /mnt/etc/skel/ ; echo 'exec cinnamon-session' >> /mnt/etc/skel/.xinitrc ; echo 'startx' >> /mnt/etc/skel/.zprofile ;;
    5) setde=' ' ;;
esac

echo -e "\nProcessador\n-----------\n\n1) AMD\t\t\t2) Intel\t\t\t3) Nao definir\n" ; echo -n "Escolha [1-3]: " ; read g
case $g in
    1) drpc="amd-ucode" ;; 2) drpc="intel-ucode" ;; 3) drprc=" " ;;
esac
clear

pacstrap /mnt base base-devel linux linux-firmware linux-headers dhcpcd nano grub xorg-server xorg-xinit xorg-xrandr wget git p7zip unrar gvfs ttf-dejavu zsh networkmanager alsa-utils $setde $drpc

echo $nmq > /mnt/etc/hostname

sed -i '/pt_BR.UTF-8/,+1 s/^#//' /mnt/etc/locale.gen

echo 'LANG=pt_BR.UTF-8' > /mnt/etc/locale.conf

arch-chroot /mnt locale-gen

arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/Recife /etc/localtime

genfstab -U /mnt >> /mnt/etc/fstab

clear ; echo -e '\nGRUB\n----\n\n1) BIOS\t\t\t2) UEFI\t\t\t3) Nao definir\n' ; echo -n 'Escolha [1-3]: ' ; read g
case $g in
    1) sleep 2 ; echo ; echo -n 'Indique o disco onde o GRUB sera instalado. Ex.: sda, sdb, sdc: ' ; read dgrb ; arch-chroot /mnt grub-install /dev/$dgrb ; mkdir -p /mnt/boot/grub/themes ; wget https://github.com/binolinux/backgrounds/raw/master/arch-pacman-invaders-1920x1080.png /mnt/boot/grub/themes/background.png ; sed -i 's/\/path\/to\/wallpaper/\/boot\/grub\/themes\/background.png/' /mnt/etc/default/grub ; sed -i '/GRUB_BACKGROUND/s/^#//' /mnt/etc/default/grub ; echo -e '\nmenuentry "Reiniciar" {\n	echo "Reiniciando o sistema..."\n	reboot\n}\n\nmenuentry "Desligar" {\n	echo "Desligando o sistema..."\n	halt\n}\n' | tee -a /mnt/etc/grub.d/40_custom ; arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg ;;
    2) arch-chroot /mnt pacman -S --needed --noconfirm efibootmgr ; arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub --recheck ; mkdir -p /mnt/boot/grub/themes ; wget https://github.com/binolinux/backgrounds/raw/master/arch-pacman-invaders-1920x1080.png /mnt/boot/grub/themes/background.png ; sed -i 's/\/path\/to\/wallpaper/\/boot\/grub\/themes\/background.png/' /mnt/etc/default/grub ; sed -i '/GRUB_BACKGROUND/s/^#//' /mnt/etc/default/grub ; echo -e '\nmenuentry "Reiniciar" {\n	echo "Reiniciando o sistema..."\n	reboot\n}\n\nmenuentry "Desligar" {\n	echo "Desligando o sistema..."\n	halt\n}\n' | tee -a /mnt/etc/grub.d/40_custom ; arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg ;;
    3) break ;;
esac

cat << EOF > /mnt/etc/vconsole.conf
KEYMAP=br-abnt2
FONT=Lat2-Terminus16
FONT_MAP=
EOF

mkdir -p /mnt/etc/X11/xorg.conf.d/
cat << EOF > /mnt/etc/X11/xorg.conf.d/01-keyboard-layout.conf
Section "InputClass"
         Identifier "Keyboard Defaults"
         MatchIsKeyboard "yes"
         Option "XkbLayout" "br"
EndSection
EOF

arch-chroot /mnt git clone https://github.com/ohmyzsh/ohmyzsh /etc/skel/.oh-my-zsh
arch-chroot /mnt git clone https://github.com/zsh-users/zsh-autosuggestions.git /etc/skel/.oh-my-zsh/plugins/zsh-autosuggestions
arch-chroot /mnt git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /etc/skel/.oh-my-zsh/plugins/zsh-syntax-highlighting
cp /mnt/etc/skel/.oh-my-zsh/templates/zshrc.zsh-template /mnt/etc/skel/.zshrc
sed -i 's/en_US/pt_BR/' /mnt/etc/skel/.zshrc ; sed -i '/pt_BR/s/^#//' /mnt/etc/skel/.zshrc
sed -i 's/(git)/(git compleat common-aliases extract zsh-autosuggestions zsh-syntax-highlighting)/' /mnt/etc/skel/.zshrc
wget https://github.com/dylanaraps/neofetch/raw/master/neofetch -O /mnt/usr/local/bin/neofetch
wget https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev -O /mnt/usr/local/bin/screenfetch
wget https://github.com/sivel/speedtest-cli/raw/master/speedtest.py -O /mnt/usr/local/bin/speedtest-cli
chmod +x /mnt/usr/local/bin/*

arch-chroot /mnt groupadd -r autologin
arch-chroot /mnt useradd -m -g users -G autologin,wheel,storage,power -s /bin/bash $nnu

clear ; echo 'senha do root '
arch-chroot /mnt passwd

echo ; echo 'senha do '$nnu' '
arch-chroot /mnt passwd $nnu
arch-chroot /mnt chsh -s /bin/zsh $nnu

sed -i '/%wheel ALL=(ALL) ALL/s/^#//' /mnt/etc/sudoers

arch-chroot /mnt systemctl enable {dhcpcd,NetworkManager} ; clear

if [ -f /mnt/etc/skel/.xinitrc ]; then
cat << EOF > /mnt/temas
#!/bin/bash
git clone https://github.com/vinceliuice/Matcha-gtk-theme /tmp/matcha ; cd /tmp/matcha ; sh install.sh -d /usr/share/themes/
git clone https://github.com/daniruiz/flat-remix-gtk /tmp/flatremix ; mv /tmp/flatremix/Flat* /usr/share/themes/
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install.sh | sh
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh | sh
papirus-folders --color teal
pacman -S --needed --noconfirm arc-icon-theme moka-icon-theme
EOF
arch-chroot /mnt sh temas
rm -f /mnt/temas
fi

arch-chroot /mnt chown -R $nnu:$nnu /home/$nnu ; arch-chroot /mnt chown -R ${nnu}:${nnu} /home/$nnu

arch-chroot /mnt pacman -Sc --noconfirm

clear ; echo -e 'Instalacao concluida. Reiniciar? [ S ou s = SIM ]' ; read yorn
    if [[ $yorn = [sSyY] ]]; then
    umount -R /mnt && reboot
    fi
    
    else
    exit
    fi
